name: Build and Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Java 22
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Set up Node.js 22
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run index.js
      run: node index.js

    - name: Release APK
      run: |
        git add RabbitLauncher0517_Patched.apk
        git commit -m "Release RabbitLauncher0517_Patched.apk"
        git push
